model:
  init_args:
    utility_score_temperature: 1.0
    utility_score_bias: -1.1
    mask_thresh: 0.60
    overlap_thresh: 0.75
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 200
        quality_head_enabled: True
        encoder:
          class_path: models.vit.ViT
data:
  class_path: datasets.ade20k_panoptic.ADE20KPanoptic
  init_args:
    check_empty_targets: True
    img_size: [1280, 1280]
    stuff_classes: [0, 1, 2, 3, 4, 5, 6, 9, 11, 13, 16, 17, 21, 25, 26, 28, 29, 34, 40, 46, 48, 51, 52, 54, 59, 60, 61, 63, 68, 77, 79, 84, 91, 94, 96, 99, 100, 101, 105, 106, 109, 113, 114, 117, 122, 128, 131, 140, 141, 145]
