model:
  init_args:
    utility_score_temperature: 1.2
    utility_score_bias: -1.0
    mask_thresh: 0.50
    overlap_thresh: 0.65
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 200
        quality_head_enabled: True
        encoder:
          class_path: models.vit.ViT
data:
  class_path: datasets.coco_instance.COCOInstance
  init_args:
    img_size: [1280, 1280]
